// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_us_slice: dynamic(() => import("./AboutUsSlice")),
  gallery_slice: dynamic(() => import("./GallerySlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
};
