// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_two_section_slice: dynamic(() => import("./AboutTwoSectionSlice")),
  about_us_slice: dynamic(() => import("./AboutUsSlice")),
  article_list_slice: dynamic(() => import("./ArticleListSlice")),
  before_after: dynamic(() => import("./BeforeAfter")),
  contact_slice: dynamic(() => import("./ContactSlice")),
  gallery_slice: dynamic(() => import("./GallerySlice")),
  hero_slice: dynamic(() => import("./HeroSlice")),
  quote_slice: dynamic(() => import("./QuoteSlice")),
  small_hero_slice: dynamic(() => import("./SmallHeroSlice")),
  team_section_slice: dynamic(() => import("./TeamSectionSlice")),
  testimonials_slice: dynamic(() => import("./TestimonialsSlice")),
};
